FROM alpine

WORKDIR /usr/src/app

ENV DOCKERIZE_VERSION v0.7.0

RUN apk update --no-cache \
    && apk add --no-cache wget openssl \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apk del wget

RUN apk add nodejs npm

RUN npm install express mysql2

RUN apk del npm

COPY hello* .

COPY proxy-reverso.js .

RUN ls . && sleep 3

CMD [ "node", "proxy-reverso.js" ]
